import random
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    random_number = random.randrange(1000,9999)
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://gymlog.ru/")
    page.get_by_role("link", name="Регистрация").click()
    # Негативные тесты регистрации
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("kdgdgk@")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("<script>alert('test')")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("SELECT * FROM users")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testnamemail.com")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testnamemail!!!@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testmail.test.test.test.test.test.testt" + str(random_number) + "@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    # Позитивные тесты регистрации
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testmail" + str(random_number) + "@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/")
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testmail" + str(random_number) + "@subdomain.mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/")
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testmail.test.test.test.test.test.tes" + str(random_number) + "@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/")
    page.locator("input[type=\"text\"]").click()
    page.locator("input[type=\"text\"]").fill("testmail.test.test.test.test.test.test" + str(random_number) + "@mail.ru")
    page.get_by_role("button", name="Начать работу бесплатно").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/")
    page.get_by_role("link", name="Вход").click()
    page.get_by_role("button", name="Войти").click()
    page.get_by_text("Запомнить").click()
    page.get_by_role("button", name="Войти").click()
    page.get_by_text("Запомнить").click()
    page.get_by_role("link", name="Регистрация").click()
    page.goto("https://gymlog.ru/profile/login/")
    # Негативные тесты авторизации
    page.locator("#email").click()
    page.locator("#email").fill("User492")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    page.get_by_label("Пароль *").click()
    page.get_by_label("Пароль *").fill("rbltJT")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    page.locator("#email").click()
    page.locator("#email").fill("lamap55129@fenxz.com")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    page.locator("#email").click()
    page.locator("#email").fill("notexistingmail@mail.ru")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    page.locator("#email").click()
    page.locator("#email").fill("testmail.test.test.test.test.test.testt" + str(random_number) + "@mail.ru")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    page.locator("#email").click()
    page.locator("#email").fill("notexistingmail@mail.ru")
    page.get_by_label("Пароль *").click()
    page.get_by_label("Пароль *").fill("notexistingpassword")
    page.get_by_role("button", name="Войти").click()
    page.reload()
    # Позитивные тесты авторизации
    page.locator("#email").click()
    page.locator("#email").fill("User492")
    page.get_by_label("Пароль *").click()
    page.get_by_label("Пароль *").fill("rbltJT")
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/profile/login/")
    page.locator("#email").click()
    page.locator("#email").fill("lamap55129@fenxz.com")
    page.get_by_label("Пароль *").click()
    page.get_by_label("Пароль *").fill("rbltJT")
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="Выйти").click()
    page.goto("https://gymlog.ru/profile/login/")
    page.get_by_role("link", name="Забыли пароль?").click()
    # Негативные тесты восстановления
    page.get_by_role("button", name="Восстановить").click()
    page.get_by_role("link", name="Регистрация").click()
    page.goto("https://gymlog.ru/profile/recovery/")
    page.get_by_role("link", name="Вход").click()
    page.goto("https://gymlog.ru/profile/recovery/")
    page.get_by_label("Электронная почта *").click()
    page.get_by_label("Электронная почта *").fill("notexistingmail@mail.ru")
    page.get_by_role("button", name="Восстановить").click()
    page.reload()
    # Позитивный тест восстановления
    page.get_by_label("Электронная почта *").click()
    page.get_by_label("Электронная почта *").fill("lamap55129@fenxz.com")
    page.get_by_role("button", name="Восстановить").click()
    page.reload()
    # Негативные тесты восстановления
    page.get_by_label("Электронная почта *").click()
    page.get_by_label("Электронная почта *").fill("lamap55129@fenxz.com")
    page.get_by_role("button", name="Восстановить").click()
    page.get_by_label("Электронная почта *").click()
    page.get_by_label("Электронная почта *").fill("lamap55129")
    page.get_by_role("button", name="Восстановить").click()
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
